[global/wm]
margin-top = 0
margin-bottom = 0

[colors]
background = #111111cc
pink = #ff79c6
black = #000000

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; PRIMARY BAR (DP-3)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[bar/primary]
monitor = DP-3
width = 100%
height = 30
bottom = true
center = true



radius = 10

background = ${colors.background}
foreground = ${colors.pink}

border-size = 1
border-color = #ff69b4

padding-left = 3
padding-right = 3

font-0 = IosevkaTerm Nerd Font Mono:size=13;2

modules-left = volume
modules-center = i3
modules-right = date

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SECONDARY BAR (HDMI-1)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[bar/secondary]
monitor = HDMI-1
width = 100%
height = 30
bottom = true

offset-x = 5%
radius = 10

background = ${colors.background}
foreground = ${colors.pink}

padding-left = 3
padding-right = 3

border-size = 1
border-color = #ff69b4

font-0 = IosevkaTerm Nerd Font Mono:size=13;2

modules-left = volume
modules-right = date

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; I3 WORKSPACES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/i3]
type = internal/i3
format = <label-state>

index-sort = true
wrapping-scroll = false

label-focused = %name%
label-focused-foreground = ${colors.black}
label-focused-background = ${colors.pink}
label-focused-padding = 2
label-focused-radius = 5

label-unfocused = %name%
label-unfocused-foreground = ${colors.pink}
label-unfocused-padding = 2

label-visible = %name%
label-visible-padding = 2

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; VOLUME
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/volume]
type = custom/script
exec = pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}'
interval = 1

label = VOL %output%
label-foreground = ${colors.pink}

scroll-up = pactl set-sink-volume @DEFAULT_SINK@ +5%
scroll-down = pactl set-sink-volume @DEFAULT_SINK@ -5%

click-left = pactl set-sink-mute @DEFAULT_SINK@ toggle

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; DATE
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/date]
type = internal/date
interval = 5

date = %B %d %Y  %H:%M
label = %date%
label-foreground = ${colors.pink}
